language: groovy
before_script: "./grailsw clean && ./grailsw refresh-dependencies --non-interactive"
script: "./grailsw test-app && ./grailsw test package-plugin"
before_deploy:
- export RELEASE_PKG_FILE=$(ls *.zip)
deploy:
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: WQQUtykxjpUu061NtWs1TDYUQRZkjNcN65xPy/AZxPekS5xfcfTXZXk9Scnn//k2p8PxRJj9ouXN9h84wZpTSMLK3WX06Xc5malEpcPSVx3bothHQn5+pwEcMg0lLcdFv2qDBoYIYh5/v1LeqcaX7UphhY9jKlKdkNX+dbc1HltbHEPA5rtuvxTSczAUtYAg+YN9C4fqOz4CN7uwwqwdPDcpuKSnTYuLJDRBLoU0OzcvEOdAKtEgV9qOL9cMgWy4DFLFeH+OC6PvDXE3vYJQYCW+Bclno8OSU1W/DvafIc9L0tXgYR0Djwecvt9A3+AbRz0QRN2Db3taFc0EmFHX8hcP7LEFn00AgX/nm7EuTVwnxEcWI35oxBFs6skKmn0X+r2wvoiOsrzOe+9wp5cMQ3PyQxXKXDHqExld9aoseuYGBS838V67qQYaFX0RNtPLaBn50EHw2r+x9KqLDSAX2qjzZKeEsO7D1sHunHFYJ1kBLbUglVFFeEXt/5mx2TWgCNlwkXRRNIWoR2KdUH21XpGTPiNvBhr7o4P3Y3r7ratBiIJ1X+tnZCz4pB16FpKQAOYFr6xRmzYMuzVCUbwpARwa9vU459j1OpiWzNnpp67LQvPu+I4kdxr+WnLKM52sxkd7o9RDkY6fjgjVCiDMdsEec0rc7m5jV2El+Wasjmo=
    file: "${RELEASE_PKG_FILE}"
    on:
      repo: willcrisis/willcrisis-mail
      tags: true
  - provider: script
    script: ./grailsw test upload-to-bintray
    on:
      tags: true
